version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0
  aws-cloudformation: circleci/aws-cloudformation@<<pipeline.parameters.dev-orb-version>>
jobs:
  deploy-cloudformation:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Deploy Cloudformation Template with new Docker image
          command: |
            aws cloudformation deploy \
            --template Code-28082021-AbhinavGupta.yml \
            --stack-name my-stack
            --region us-east-1

workflows:
  cloudformation:
    jobs:
      - deploy-cloudformation
