name: 'stack creation using CloudFormation'

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  create_stack:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.My_key }}
          aws-secret-access-key: ${{ secrets.My_key_secret }}
          aws-region: ap-southeast-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: My-Stack
          template: Code-28082021-AbhinavGupta.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: "s3Versioning=Enabled"
          capabilities : CAPABILITY_IAM
